Window functions section
palantir/pyspark-style-guide pull request #6
Opened 2020-12-04 11:35 UTC by mattsills

2020-12-04 13:05 UTC, asmello requested changes
This is a great idea. Been bit by unintuitive/unclear defaults for frame ranges a bunch of times.

Added a few comments gathered from an internal discussion. I'll try to make some contributions later today.

2020-12-04 13:05 UTC, asmello commented on README.md
> +Always specify an explicit frame when using window functions, using either [row frames](https://spark.apache.org/docs/3.0.1/api/java/org/apache/spark/sql/expressions/WindowSpec.html#rowsBetween-long-
Should we point to the latest documentation, or pin to a version? If we don't pin the link may break at a future release, but that's potentially better than pointing to stale documentation.

2020-12-04 13:05 UTC, asmello commented on README.md
> +# => [Row(key=u'a', sum=10), Row(key=u'a', sum=10), Row(key=u'a', sum=10), Row(key=u'a', sum=10)]
Should replace with Python 3 output (u-strings are Python 2).

2020-12-04 13:05 UTC, asmello commented on README.md
> +df.select('key', F.sum('num').over(w1).alias('sum')).collect()
While this works to illustrate the problem, I think we can make a much stronger case for not relying on defaults if we include `F.lead()` and `F.last()` in the examples. I find the latter particularly unintuitive.

2020-12-04 13:05 UTC, asmello commented on README.md
> +# Window Functions
We should also add a warning that windows with empty `partitionBy()` will force coalescing into a single partition. This can be very bad for performance.

2020-12-04 15:00 UTC, ntrinquier approved these changes

2020-12-04 15:02 UTC, ntrinquier commented
We could also add it as an anti-pattern [here](https://github.palantir.build/foundry/antipatterns-plugin).
As well as what @asmello said about empty `partitionBy`.

2020-12-04 17:21 UTC, melonhead901 commented on README.md
> +# Window Functions
+1 see this a lot from clients

2020-12-07 20:55 UTC, asmello commented
Implemented my suggestions :+1:

2020-12-08 08:47 UTC, fmsf approved these changes
I don't have a strong opinion on windows/partitions, but this was interesting to read and sounds sane. good stuff!

2020-12-08 09:21 UTC, asmello approved these changes

2020-12-08 09:24 UTC, merged